import Head from "next/head";
import styles from "@/styles/Home.module.css";

import Map from "@/components/Map";

export default function Home() {
  return (
    <>
      <Head>
        <title>Show Coordinates</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <span>
            A simple React client app for fetching coordinates, then showing
            them in a&nbsp;
            <a href="https://docs.mapbox.com/mapbox-gl-js/guides/">Mapbox</a>
            &nbsp;view
          </span>
        </div>
        <div className={styles.center}></div>
        <Map />
      </main>
    </>
  );
}
